name: Build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v3
      - run: git clone --recursive https://github.com/theos/theos.git ~/theos
      - run: export THEOS=~/theos && make package
      - uses: actions/upload-artifact@v3
        with:
          name: AAIPUBG
          path: .theos/obj/*.dylib
